JBRes-1996 Add a Benchmarking Action
plan-research/project-minimization pull request #46
Opened 2024-12-20 16:02 UTC by Mike-Wazovsky

## Description

Here should be more info about PR:
- context/purpose for implementing changes;
- detailed descriptions of the changes made;
- link to a documentation.

## How to test

### Automated tests

Please specify the _automated tests_ for your code changes: you should either mention the existing tests or add the new ones.

For example:
> Translation and parsing of Kotlinc errors verified with tests: `project-minimization-plugin/src/test/kotlin/KotlincExceptionTranslatorTests.kt`

### Manual tests

If it's impossible to provide the automated tests, please provide a description of how to verify the changes manually. 

## Self-check list

- [ ] PR **title** and **description** are clear and aligned with a format.
- [ ] I've added enough **comments** to my code, particularly in hard-to-understand areas. 
- [ ] The functionality I've repaired, changed or added is covered with **automated tests**.
- [ ] **Manual tests** have been provided _optionally_.
- [ ] The **documentation** for the functionality I've been working on is up-to-date/provided.
- [ ] The **link** to this PR is commented on in the corresponding **YT ticket**.

Hint: [x] is a marked item

2025-01-14 16:12 UTC, SBOne-Kenobi requested changes
Overall very good quality and structure of the code, but there are some comments

P.S. I will try to test it manually a bit later

2025-01-14 16:12 UTC, SBOne-Kenobi commented on project-minimization-plugin/build.gradle.kts
> +    implementation("com.charleskorn.kaml:kaml:0.59.0")
use `libs.kaml`

2025-01-14 16:12 UTC, SBOne-Kenobi commented on project-minimization-plugin/src/main/kotlin/org/plan/research/minimization/plugin/logging/LogParser.kt
> +fun main(args: Array<String>) {
It's better to create a separate module for scripts like this, for instance `project-minimization-scripts` or `project-minimization-statistics`

2025-01-14 16:12 UTC, SBOne-Kenobi commented on project-minimization-plugin/src/main/kotlin/org/plan/research/minimization/plugin/logging/PropertyTesterWithStatistics.kt
> +        val processBuilder = ProcessBuilder("cloc", path)
It's better to try to use this
https://github.com/AlDanial/cloc?tab=readme-ov-file#java-programmatic-interface-

2025-01-14 16:12 UTC, SBOne-Kenobi commented on project-minimization-plugin/src/main/kotlin/org/plan/research/minimization/plugin/services/BenchmarkService.kt
> +        }
```suggestion
        val config = readConfig().getOrNull() ?: return@launch
```

2025-01-14 16:12 UTC, SBOne-Kenobi commented on project-minimization-plugin/src/main/resources/META-INF/plugin.xml
> +        <notificationGroup id="org.plan.research.minimization.benchmark.result"
I think you don't need it, or I missed something?

2025-01-14 16:12 UTC, SBOne-Kenobi commented on project-minimization-plugin/src/main/kotlin/org/plan/research/minimization/plugin/services/BenchmarkService.kt
> +                            }
Some strange construction, what did you try to do?

2025-01-14 16:12 UTC, SBOne-Kenobi commented on project-minimization-plugin/src/main/kotlin/org/plan/research/minimization/plugin/services/BenchmarkService.kt
> +                minimizationService.minimizeProject { context -> cont.resume(context) }
I see now that there are no problems with using the private method `minimizeProjectImpl`. I had some concerns about background progress, but we already have some here. So what you can do:
1. make `minimizeProjectImpl` public
2. rename `minimizeProjectImpl` to `minimizeProjectAsync`
3. get rid of suspendCancellableCoroutine

2025-01-20 17:22 UTC, Mike-Wazovsky commented
Don't forget to add cleaning scripts

2025-01-21 08:25 UTC, SBOne-Kenobi requested changes
Everything looks good :goat: 
There are some minor comments and one comment on the statistics-gathering strategy. As soon as they will be fixed, we will merge it

2025-01-21 08:25 UTC, SBOne-Kenobi commented on project-minimization-plugin/src/main/kotlin/org/plan/research/minimization/plugin/execution/SameExceptionPropertyTester.kt
> +                .withStatistics()
Will it always be executed with statistics? I think we need a separate flag/setting to enable this only for benchmarking

2025-01-21 08:25 UTC, SBOne-Kenobi commented on project-minimization-plugin/src/main/kotlin/org/plan/research/minimization/plugin/services/BenchmarkService.kt
> +    }
```suggestion
    private suspend fun closeProject(project: Project) {
        ProjectManagerEx.getInstanceEx().forceCloseProjectAsync(project)
    }
```

2025-01-21 08:25 UTC, SBOne-Kenobi commented on project-minimization-plugin/src/main/kotlin/org/plan/research/minimization/plugin/logging/PropertyTesterWithStatistics.kt
> +        CLOC.command()
I think it's better to run it using `withContext(Dispatchers.IO)` because it communicates with the file system directly

[Useful link](https://plugins.jetbrains.com/docs/intellij/coroutine-dispatchers.html#io-dispatcher)

2025-01-21 11:44 UTC, SBOne-Kenobi approved these changes
LGTM :+1:

2025-01-21 12:05 UTC, merged